POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "john shmoe",
  "number": "12-34-567890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "john shmoe"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mary Poppendieck",
  "number": "12-34-567890"
}
